python ./opensora/train/train_causalvae.py \
    --exp_name "vae888_8_decoder_seg" \
    --batch_size 1 \
    --precision bf16 \
    --max_steps 4000000 \
    --save_steps 8000 \
    --output_dir results/vae_seg \
    --video_num_frames 17 \
    --resolution 224 \
    --sample_rate 1 \
    --dataset mixed \
    --n_nodes 1 \
    --devices 1 \
    --num_workers 4 
